### ISSUE TITLE
Issue with PCB trace to expander header (REV2.1 combined)

### ISSUE THREAD

**Issue by misterpulcri** [TomWhitwell/Spring-Reverb-Mk-2#18]
In the SpringReverbRev2.1combined board the PCB trace falls sort of reaching the expander header pin 1

![MTM-SpringMK2-pcb error](https://github.com/TomWhitwell/Spring-Reverb-Mk-2/assets/96618977/257a84a2-1b65-43c4-9a04-2765abc8263b)

As I am using the expander in lieu of the PCB mpunted RCA connectors this resulted in no signal being sent to the tank. I was able to work arounf this by soldering a wire between pin 1 and one of the ring PCB holes for the send RCA connector.

**Comment by TomWhitwell** [comment]
Apologies - have pushed a new Eagle file and gerbers
