### ISSUE TITLE
I'd like to add Feedback to my mkI Spring Reverb

### ISSUE THREAD

**Issue by MickGlossop** [TomWhitwell/Spring-Reverb-Mk-2#3]
I have an new mkII kit to build, but i'd like to add the feedback function to my mk I unit.

Would that be an easy mod?

Mick

**Comment by TomWhitwell** [comment]
It's very easy to patch using a mixer and a couple of mults or stackables, but I'm not sure how you'd do it in the existing module.

**Comment by MickGlossop** [comment]
Thanks Tom. I thought as much. I've successfully patched an external solution using a mult and an attenuverter, for the +/- feedback option.
